export enum Pairs {
  BTCUSDT = 'BTCUSDT',
  ETHUSDT = 'ETHUSDT',
  ADAUSDT = 'ADAUSDT',
  SOLUSDT = 'SOLUSDT',
  SLPUSDT = 'SLPUSDT',
  CHZUSDT = 'CHZUSDT',
  CAKEUSDT = 'CAKEUSDT',
  LTCUSDT = 'LTCUSDT',
  XRPUSDT = 'XRPUSDT',
  DOTUSDT = 'DOTUSDT',
}
