version: '3.9'
services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pairs
    ports:
      - '3306:3306'
    volumes:
      - technical-challenges:/var/lib/mysql

volumes:
  technical-challenges:
